
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 18;
  public static final int Parentesis_a = 17;
  public static final int poligono = 6;
  public static final int Suma = 13;
  public static final int Numero = 20;
  public static final int circulo = 3;
  public static final int coma = 19;
  public static final int animar = 9;
  public static final int T_color = 2;
  public static final int linea = 5;
  public static final int EOF = 0;
  public static final int Division = 16;
  public static final int Resta = 14;
  public static final int curva = 8;
  public static final int error = 1;
  public static final int cuadrado = 7;
  public static final int SLinea = 21;
  public static final int graficar = 12;
  public static final int rectangulo = 4;
  public static final int anterior = 11;
  public static final int objeto = 10;
  public static final int Multiplicacion = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_color",
  "circulo",
  "rectangulo",
  "linea",
  "poligono",
  "cuadrado",
  "curva",
  "animar",
  "objeto",
  "anterior",
  "graficar",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Parentesis_a",
  "Parentesis_c",
  "coma",
  "Numero",
  "SLinea"
  };
}

